/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d2d9f4",
        "inverse-surface": "#283044",
        "primary-fixed-dim": "#b7c4fd",
        "on-secondary-container": "#fefcff",
        "primary": "#000f3f",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed": "#1e1b16",
        "on-tertiary": "#ffffff",
        "tertiary": "#16140f",
        "surface-container-low": "#f2f3ff",
        "on-error": "#ffffff",
        "surface-variant": "#dae2fd",
        "primary-fixed": "#dce1ff",
        "surface-container-high": "#e2e7ff",
        "error": "#ba1a1a",
        "inverse-on-surface": "#eef0ff",
        "surface-container": "#eaedff",
        "tertiary-container": "#2b2822",
        "surface-container-highest": "#dae2fd",
        "on-primary-fixed": "#071747",
        "inverse-primary": "#b7c4fd",
        "outline-variant": "#c6c5d0",
        "on-surface": "#131b2e",
        "on-primary-container": "#808dc2",
        "on-tertiary-fixed-variant": "#4a4640",
        "outline": "#767680",
        "on-surface-variant": "#45464f",
        "on-tertiary-container": "#948f87",
        "primary-container": "#172554",
        "tertiary-fixed-dim": "#ccc6bd",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#dbe1ff",
        "on-primary-fixed-variant": "#374475",
        "secondary-container": "#316bf3",
        "on-secondary-fixed-variant": "#003ea8",
        "surface": "#faf8ff",
        "surface-bright": "#faf8ff",
        "on-background": "#131b2e",
        "tertiary-fixed": "#e8e1d9",
        "surface-tint": "#4f5c8e",
        "secondary": "#0051d5",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#00174b",
        "on-primary": "#ffffff",
        "background": "#faf8ff",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "4px",
        "margin-mobile": "16px",
        "sm": "16px",
        "md": "24px",
        "margin-desktop": "64px",
        "xl": "80px",
        "gutter": "24px",
        "xs": "8px",
        "lg": "48px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "caption": ["Inter", "sans-serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "1.7", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "display-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "caption": ["12px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "headline-sm": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
